### ISSUE TITLE
python2 group names

### ISSUE THREAD

**Issue by fupduck** [cholin/resign#11]
Python2 gets strange group names from dbus.

i.e.
u'ZGJ1cy5BcnJheShbZGJ1cy5CeXRlKDU3KSwgZGJ1cy5CeXRlKDIyOSksIGRidXMuQnl0ZSg2KSwgZGJ1cy5CeXRlKDczKSwgZGJ1cy5CeXRlKDE2MCksIGRidXMuQnl0ZSgyNTMpLCBkYnVzLkJ5dGUoMTA2KSwgZGJ1cy5CeXRlKDE5OSksIGRidXMuQnl0ZSgxNzMpLCBkYnVzLkJ5d[…]'

instead of 
u'OeUGSxxxxxxxxOgyw=='

**Comment by fupduck** [comment]
the function bytes workes differentyl in python2 and python3
the error/enhancement is fixed in #9

**Comment by cholin** [comment]
Merged #9 and therefor should be fixed.
